# Generated by Django 3.2.4 on 2021-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
